#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v21
# autospec commit: e822d6e48dc0
#
Name     : perl-Test-ExpectAndCheck
Version  : 0.07
Release  : 6
URL      : https://cpan.metacpan.org/authors/id/P/PE/PEVANS/Test-ExpectAndCheck-0.07.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/P/PE/PEVANS/Test-ExpectAndCheck-0.07.tar.gz
Summary  : 'C<expect/check>-style unit testing with object methods'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Test-ExpectAndCheck-license = %{version}-%{release}
Requires: perl-Test-ExpectAndCheck-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(Test::Deep)
BuildRequires : perl(Test::Future::Deferred)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
NAME
Test::ExpectAndCheck - expect/check-style unit testing with object
methods
SYNOPSIS

%package dev
Summary: dev components for the perl-Test-ExpectAndCheck package.
Group: Development
Provides: perl-Test-ExpectAndCheck-devel = %{version}-%{release}
Requires: perl-Test-ExpectAndCheck = %{version}-%{release}

%description dev
dev components for the perl-Test-ExpectAndCheck package.


%package license
Summary: license components for the perl-Test-ExpectAndCheck package.
Group: Default

%description license
license components for the perl-Test-ExpectAndCheck package.


%package perl
Summary: perl components for the perl-Test-ExpectAndCheck package.
Group: Default
Requires: perl-Test-ExpectAndCheck = %{version}-%{release}

%description perl
perl components for the perl-Test-ExpectAndCheck package.


%prep
%setup -q -n Test-ExpectAndCheck-0.07
cd %{_builddir}/Test-ExpectAndCheck-0.07
pushd ..
cp -a Test-ExpectAndCheck-0.07 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Test-ExpectAndCheck
cp %{_builddir}/Test-ExpectAndCheck-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/perl-Test-ExpectAndCheck/ff3cb0dfd45f53bab83fc8e6480335b7afdc4bbe || :
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Test::ExpectAndCheck.3
/usr/share/man/man3/Test::ExpectAndCheck::Future.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Test-ExpectAndCheck/ff3cb0dfd45f53bab83fc8e6480335b7afdc4bbe

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
